#!/bin/bash
# Author: Tibor Molnár
# Date: 23rd of July 2023
# Description: de-activate users who haven't logged in for some time
# Modified: 23rd of July 2023

# last log -b 90 -> users who have not logged in in the past 90 days
# NOTE: this greps only the 'test' accounts, you can change it as you wish
# awk greps the username
a=`lastlog -b 90 | tail -n+2 | grep 'test' | awk '{print $1}'`

for i in $a
do
	# Print out the account being disable
	echo "Account being disabled: $i"
	# disable accounts
	usermod -L $i
done
