#!/bin/bash
# Author: Tibor Molnár
# Date: 23rd of July 2023
# Descpription: check which users logged onto the system by date
# Modified: 23rd of July 2023

# --------------------------
# Demo - who logged in today
# Get today's date - Day Month Date - Fri August 15
#today=`date | awk '{print $1,$2,$3}'`

# Check who logged in "last", $today is in quotes to pass it as a whole string to grep
#last | grep "$today"
# --------------------------

# Same task as above, but ask for user input to define the date they are looking for
# "" is needed because I have () in there
echo --------------
echo Answer the below questions to get who logged in a given day
echo
echo "NOTE: the data is from the output of the "last" command, follow the format from that commands output"
echo
echo "Expected format: Fri August 15 (day-month-date)"
echo --------------
echo "Please enter day (e.g. Mon)"
read day
echo
echo "Please enter month (e.g. Aug)"
read month
echo "Please enter date (e.g. 28)"
read date
echo
# grep the wanted info from last, awk grabbes only the username
# if you want full information then remove awk or edit it as you wish
last | grep "$day $month $date" | awk '{print $1}'
echo
echo -- Script ends
